#include "codegen.h"
#include <algorithm>
#include <cctype>
#include <fstream>
#include <stdexcept>
// IA
#include <unordered_set>

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────
// IA
static std::string escapeForStringLiteral(const std::string& s) {
    std::string out;
    out.reserve(s.size());
    for (char c : s) {
        if (c == '"')       out += "\\\"";
        else if (c == '\\') out += "\\\\";
        else                out += c;
    }
    return out;
}

static std::string toUpper(std::string s) {
    std::transform(s.begin(), s.end(), s.begin(),
                   [](unsigned char c) { return static_cast<char>(std::toupper(c)); });
    return s;
}

// ─────────────────────────────────────────────────────────────────────────────
// CodeGen::generate
//
// Emits a C++20 header that uses non-type template parameters (NTTP) to
// encode HTTP method and path at compile time, and stores function pointers
// to the handlers inside a std::tuple — the RouteTable.
//
// Generated layout:
//
//   FixedString<N>          — NTTP helper: allows string literals as template
//                             args (C++20 class non-type template parameters)
//
//   Route<Method,Path,Fn>   — compile-time route descriptor
//                             - ::method / ::path  → constexpr string views
//                             - ::handler          → constexpr function pointer
//                             - ::invoke(args...)  → calls the handler
//
//   inline <RetType> <name>(<params>) { <body> }
//                           — the actual handler implementations, inlined so
//                             the header is self-contained
//
//   RouteTable              — std::tuple<Route<...>, ...>
//                             Iterable at compile time via std::apply / index_sequence.
//                             Zero heap cost; resolved entirely by the compiler.
//
//   route_count             — constexpr number of routes
// ─────────────────────────────────────────────────────────────────────────────
std::string CodeGen::generate(const std::vector<RouteNode>& routes) {
    // IA
    std::unordered_set<std::string> seenNames;
    for (const auto& r : routes) {
        if (!seenNames.insert(r.funcName).second)
            throw std::runtime_error(
                "Nombre de funcion duplicado: '" + r.funcName + "'. " +
                "Cada handler debe tener un nombre unico");
    }

    std::string out;
    out.reserve(1024 + routes.size() * 256);

    // ── File header ───────────────────────────────────────────────────────────
    out += "// ================================================================\n";
    out += "// AUTO-GENERATED by cgua-precomp — DO NOT EDIT\n";
    out += "// ================================================================\n";
    out += "#pragma once\n";
    out += "#include <cstddef>\n";
    out += "#include <string_view>\n";
    out += "#include <tuple>\n";
    out += "\n";

    out += "namespace cgua {\n\n";

    // ── FixedString: NTTP string wrapper (C++20) ──────────────────────────────
    // Allows string literals to be used as non-type template parameters, e.g.:
    //   Route<"GET", "/api/users", getUsers>
    // The compiler deduces N from the string literal length.
    out += "// ── FixedString: compile-time string as a non-type template parameter ──────\n";
    out += "template<std::size_t N>\n";
    out += "struct FixedString {\n";
    out += "    constexpr FixedString(const char (&s)[N]) noexcept {\n";
    out += "        for (std::size_t i = 0; i < N; ++i) data[i] = s[i];\n";
    out += "    }\n";
    out += "    constexpr std::string_view view() const noexcept {\n";
    out += "        return {data, N - 1}; // N-1 excludes the null terminator\n";
    out += "    }\n";
    out += "    char data[N]{};\n";
    out += "};\n\n";

    // ── Route descriptor ──────────────────────────────────────────────────────
    out += "// ── Route descriptor — all fields resolved at compile time ──────────────────\n";
    out += "template<FixedString Method, FixedString Path, auto Handler>\n";
    out += "struct Route {\n";
    out += "    static constexpr std::string_view method  = Method.view();\n";
    out += "    static constexpr std::string_view path    = Path.view();\n";
    out += "    static constexpr auto             handler = Handler;\n";
    out += "\n";
    out += "    // Dispatch: forward any arguments directly to the handler\n";
    out += "    template<typename... Args>\n";
    out += "    static constexpr auto invoke(Args&&... args)\n";
    out += "        noexcept(noexcept(Handler(static_cast<Args&&>(args)...)))\n";
    out += "    {\n";
    out += "        return Handler(static_cast<Args&&>(args)...);\n";
    out += "    }\n";
    out += "};\n\n";

    // ── Handler implementations ───────────────────────────────────────────────
    out += "// ── Handler implementations ───────────────────────────────────────────────────\n";
    for (const auto& r : routes) {
        out += "inline " + r.returnType + " " + r.funcName +
               "(" + r.rawParams + ") {" + r.body + "}\n\n";
    }

    // ── Route table ───────────────────────────────────────────────────────────
    // A std::tuple where each element is a Route<> specialisation.
    // At compile time a framework can iterate with std::apply or an index_sequence
    // to build a dispatch table — zero runtime overhead, zero heap allocations.
    out += "// ── RouteTable: compile-time tuple of all routes ────────────────────────────\n";
    out += "using RouteTable = std::tuple<\n";
    for (std::size_t i = 0; i < routes.size(); ++i) {
        // IA
        out += "    Route<\"" + toUpper(routes[i].metodo) + "\", " +
               "\"" + escapeForStringLiteral(routes[i].ruta) + "\", " +
               routes[i].funcName + ">";
        if (i + 1 < routes.size()) out += ",";
        out += "\n";
    }
    out += ">;\n\n";

    out += "inline constexpr std::size_t route_count = std::tuple_size_v<RouteTable>;\n\n";

    out += "} // namespace cgua\n";

    return out;
}

// ─────────────────────────────────────────────────────────────────────────────
// CodeGen::writeToFile
// ─────────────────────────────────────────────────────────────────────────────
void CodeGen::writeToFile(const std::vector<RouteNode>& routes,
                          const std::string& outPath) {
    std::ofstream file(outPath);
    if (!file.is_open())
        throw std::runtime_error("No se pudo escribir: " + outPath);
    file << generate(routes);
    if (!file)
        throw std::runtime_error("Error al escribir: " + outPath);
}
