// ================================================================
// AUTO-GENERATED by cgua-precomp — DO NOT EDIT
// ================================================================
#pragma once
#include <cstddef>
#include <string_view>
#include <tuple>

namespace cgua {

// ── FixedString: compile-time string as a non-type template parameter ──────
template<std::size_t N>
struct FixedString {
    constexpr FixedString(const char (&s)[N]) noexcept {
        for (std::size_t i = 0; i < N; ++i) data[i] = s[i];
    }
    constexpr std::string_view view() const noexcept {
        return {data, N - 1}; // N-1 excludes the null terminator
    }
    char data[N]{};
};

// ── Route descriptor — all fields resolved at compile time ──────────────────
template<FixedString Method, FixedString Path, auto Handler>
struct Route {
    static constexpr std::string_view method  = Method.view();
    static constexpr std::string_view path    = Path.view();
    static constexpr auto             handler = Handler;

    // Dispatch: forward any arguments directly to the handler
    template<typename... Args>
    static constexpr auto invoke(Args&&... args)
        noexcept(noexcept(Handler(static_cast<Args&&>(args)...)))
    {
        return Handler(static_cast<Args&&>(args)...);
    }
};

// ── Handler implementations ───────────────────────────────────────────────────
inline Response getUsers(Request req) {
    return Response::ok(db.all<User>());
}

inline Response createUser(Request req) {
    auto body = req.json<User>();
    db.insert(body);
    return Response::created();
}

inline Response getUserById(Request req) {
    auto id = req.param("id");
    return Response::ok(db.find<User>(id));
}

inline Response updateUser(Request req) {
    auto id   = req.param("id");
    auto body = req.json<User>();
    db.update<User>(id, body);
    return Response::ok();
}

inline Response deleteUser(Request req) {
    auto id = req.param("id");
    db.remove<User>(id);
    return Response::noContent();
}

inline Response healthCheck(Request req) {
    return Response::ok("OK");
}

inline Response login(Request req) {
    auto creds = req.json<Credentials>();
    auto token = auth.login(creds);
    return Response::ok(token);
}

inline Response logout(Request req) {
    auth.invalidate(req.header("Authorization"));
    return Response::noContent();
}

// ── RouteTable: compile-time tuple of all routes ────────────────────────────
using RouteTable = std::tuple<
    Route<"GET", "api/users", getUsers>,
    Route<"POST", "api/users", createUser>,
    Route<"GET", "api/users/:id", getUserById>,
    Route<"PUT", "api/users/:id", updateUser>,
    Route<"DELETE", "api/users/:id", deleteUser>,
    Route<"GET", "health", healthCheck>,
    Route<"POST", "api/auth/login", login>,
    Route<"POST", "api/auth/logout", logout>
>;

inline constexpr std::size_t route_count = std::tuple_size_v<RouteTable>;

} // namespace cgua
